CREATE SCHEMA IF NOT EXISTS geral;
CREATE SCHEMA IF NOT EXISTS eventual;
CREATE SCHEMA IF NOT EXISTS web;

CREATE TABLE IF NOT EXISTS web.papel (
    nome text PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS geral.empresa (
    cnpj text PRIMARY KEY,
    nome text NOT NULL,
    nome_fantasia text,
    email text,
    telefone text,
    endereco text,
    cep text,
    endereco_numero text,
    endereco_complemento text,
    bairro text,
    cidade text,
    estado text
);

CREATE TABLE IF NOT EXISTS geral.veiculo (
    placa text PRIMARY KEY,
    chassi_numero text,
    renavan text,
    modelo text,
    fretamento_veiculo_tipo_nome text,
    potencia_motor integer,
    cor_principal_nome text,
    numero_lugares integer,
    empresa_cnpj text REFERENCES geral.empresa(cnpj),
    ano_fabricacao integer,
    modelo_ano integer,
    veiculo_combustivel_nome text,
    data_inclusao_eventual date
);

CREATE TABLE IF NOT EXISTS eventual.motorista (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_cnpj text REFERENCES geral.empresa(cnpj),
    cpf text NOT NULL,
    cnh text NOT NULL,
    email text,
    nome text,
    criado_em timestamp without time zone NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS web.usuario (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    papel_nome text NOT NULL,
    email text NOT NULL,
    nome text NOT NULL,
    cpf text,
    data_nascimento date,
    telefone text,
    senha text,
    empresa_cnpj text REFERENCES geral.empresa(cnpj),
    criado_em timestamp without time zone NOT NULL DEFAULT now(),
    atualizado_em timestamp without time zone NOT NULL DEFAULT now(),
    ativo boolean NOT NULL DEFAULT true,
    email_validado boolean NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS eventual.fluxo_pendencia (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    criado_em timestamp without time zone NOT NULL DEFAULT now(),
    entidade_tipo text NOT NULL,
    entidade_id text NOT NULL,
    status text NOT NULL,
    analista text,
    motivo text,
    dados_propostos jsonb
);

CREATE TABLE IF NOT EXISTS eventual.status_pendencia (
    status text PRIMARY KEY,
    nome text NOT NULL
);

INSERT INTO eventual.status_pendencia (status, nome) VALUES
    ('INCOMPLETO', 'Incompleto'),
    ('AGUARDANDO_ANALISE', 'Aguardando Análise'),
    ('EM_ANALISE', 'Em Análise'),
    ('APROVADO', 'Aprovado'),
    ('REJEITADO', 'Rejeitado')
ON CONFLICT (status) DO NOTHING;

CREATE OR REPLACE FUNCTION eventual.fn_analista_obrigatorio() RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.status NOT IN ('AGUARDANDO_ANALISE', 'INCOMPLETO') THEN
        IF NEW.analista IS NULL OR btrim(NEW.analista) = '' THEN
            RAISE EXCEPTION 'analista cannot be NULL when status = %', NEW.status;
        END IF;
    END IF;

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_analista_obrigatorio ON eventual.fluxo_pendencia;
CREATE TRIGGER trg_analista_obrigatorio
BEFORE INSERT OR UPDATE ON eventual.fluxo_pendencia
FOR EACH ROW EXECUTE FUNCTION eventual.fn_analista_obrigatorio();

CREATE TABLE IF NOT EXISTS eventual.documento_tipo (
    nome text PRIMARY KEY,
    descricao text,
    obrigatorio boolean NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS eventual.documento_tipo_vinculo (
    tipo_nome text NOT NULL REFERENCES eventual.documento_tipo(nome),
    entidade_tipo text NOT NULL,
    PRIMARY KEY (tipo_nome, entidade_tipo)
);

CREATE TABLE IF NOT EXISTS eventual.documento (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    documento_tipo_nome text NOT NULL REFERENCES eventual.documento_tipo(nome),
    conteudo bytea NOT NULL,
    nome_arquivo text NOT NULL,
    content_type text NOT NULL DEFAULT 'application/pdf',
    tamanho bigint,
    hash text,
    data_upload timestamp without time zone NOT NULL DEFAULT now(),
    validade date,
    fluxo_pendencia_id integer REFERENCES eventual.fluxo_pendencia(id),
    aprovado_em timestamp without time zone
);

CREATE TABLE IF NOT EXISTS eventual.documento_empresa (
    id integer PRIMARY KEY REFERENCES eventual.documento(id) ON DELETE CASCADE,
    empresa_cnpj text NOT NULL REFERENCES geral.empresa(cnpj)
);

CREATE TABLE IF NOT EXISTS eventual.documento_veiculo (
    id integer PRIMARY KEY REFERENCES eventual.documento(id) ON DELETE CASCADE,
    veiculo_placa text NOT NULL REFERENCES geral.veiculo(placa)
);

CREATE TABLE IF NOT EXISTS eventual.documento_motorista (
    id integer PRIMARY KEY REFERENCES eventual.documento(id) ON DELETE CASCADE,
    motorista_id integer NOT NULL REFERENCES eventual.motorista(id)
);

CREATE OR REPLACE VIEW eventual.v_pendencia_atual AS
SELECT DISTINCT ON (fp.entidade_tipo, fp.entidade_id)
    fp.id,
    fp.entidade_tipo,
    fp.entidade_id,
    fp.status,
    fp.analista,
    fp.criado_em,
    fp.motivo,
    fp.dados_propostos
FROM eventual.fluxo_pendencia fp
ORDER BY fp.entidade_tipo, fp.entidade_id, fp.criado_em DESC, fp.id DESC;
