CREATE SCHEMA IF NOT EXISTS geral;
CREATE SCHEMA IF NOT EXISTS eventual;
CREATE SCHEMA IF NOT EXISTS web;

CREATE TABLE IF NOT EXISTS web.papel (
    nome text PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS geral.empresa (
    cnpj text PRIMARY KEY,
    nome text NOT NULL,
    nome_fantasia text,
    email text,
    telefone text,
    endereco text,
    cep text,
    endereco_numero text,
    endereco_complemento text,
    bairro text,
    cidade text,
    estado text
);

CREATE TABLE IF NOT EXISTS geral.veiculo (
    placa text PRIMARY KEY,
    chassi_numero text,
    renavan text,
    modelo text,
    fretamento_veiculo_tipo_nome text,
    potencia_motor integer,
    cor_principal_nome text,
    numero_lugares integer,
    empresa_cnpj text REFERENCES geral.empresa(cnpj),
    ano_fabricacao integer,
    modelo_ano integer,
    veiculo_combustivel_nome text,
    data_inclusao_eventual date
);

CREATE TABLE IF NOT EXISTS eventual.motorista (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_cnpj text REFERENCES geral.empresa(cnpj),
    cpf text NOT NULL,
    cnh text NOT NULL,
    email text,
    nome text,
    criado_em timestamp without time zone NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS web.usuario (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    papel_nome text NOT NULL,
    email text NOT NULL,
    nome text NOT NULL,
    cpf text,
    data_nascimento date,
    telefone text,
    senha text,
    empresa_cnpj text REFERENCES geral.empresa(cnpj),
    criado_em timestamp without time zone NOT NULL DEFAULT now(),
    atualizado_em timestamp without time zone NOT NULL DEFAULT now(),
    ativo boolean NOT NULL DEFAULT true,
    email_validado boolean NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS eventual.fluxo_pendencia (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    criado_em timestamp without time zone NOT NULL DEFAULT now(),
    entidade_tipo text NOT NULL,
    entidade_id text NOT NULL,
    status text NOT NULL,
    analista text,
    motivo text,
    dados_propostos jsonb
);

CREATE TABLE IF NOT EXISTS eventual.status_pendencia (
    status text PRIMARY KEY,
    nome text NOT NULL
);

INSERT INTO eventual.status_pendencia (status, nome) VALUES
    ('INCOMPLETO', 'Incompleto'),
    ('AGUARDANDO_ANALISE', 'Aguardando Análise'),
    ('EM_ANALISE', 'Em Análise'),
    ('APROVADO', 'Aprovado'),
    ('REJEITADO', 'Rejeitado')
ON CONFLICT (status) DO NOTHING;

CREATE OR REPLACE FUNCTION eventual.fn_analista_obrigatorio() RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.status NOT IN ('AGUARDANDO_ANALISE', 'INCOMPLETO') THEN
        IF NEW.analista IS NULL OR btrim(NEW.analista) = '' THEN
            RAISE EXCEPTION 'analista cannot be NULL when status = %', NEW.status;
        END IF;
    END IF;

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_analista_obrigatorio ON eventual.fluxo_pendencia;
CREATE TRIGGER trg_analista_obrigatorio
BEFORE INSERT OR UPDATE ON eventual.fluxo_pendencia
FOR EACH ROW EXECUTE FUNCTION eventual.fn_analista_obrigatorio();

CREATE TABLE IF NOT EXISTS eventual.documento_tipo (
    nome text PRIMARY KEY,
    descricao text,
    obrigatorio boolean NOT NULL DEFAULT false,
    permite_multiplos boolean NOT NULL DEFAULT false
);

ALTER TABLE eventual.documento_tipo
    ADD COLUMN IF NOT EXISTS permite_multiplos boolean NOT NULL DEFAULT false;

CREATE TABLE IF NOT EXISTS eventual.documento_tipo_vinculo (
    tipo_nome text NOT NULL REFERENCES eventual.documento_tipo(nome),
    entidade_tipo text NOT NULL,
    PRIMARY KEY (tipo_nome, entidade_tipo)
);

CREATE TABLE IF NOT EXISTS eventual.documento (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    documento_tipo_nome text NOT NULL REFERENCES eventual.documento_tipo(nome),
    conteudo bytea NOT NULL,
    nome_arquivo text NOT NULL,
    content_type text NOT NULL DEFAULT 'application/pdf',
    tamanho bigint,
    hash text,
    data_upload timestamp without time zone NOT NULL DEFAULT now(),
    validade date,
    fluxo_pendencia_id integer REFERENCES eventual.fluxo_pendencia(id),
    aprovado_em timestamp without time zone
);

CREATE TABLE IF NOT EXISTS eventual.documento_empresa (
    id integer PRIMARY KEY REFERENCES eventual.documento(id) ON DELETE CASCADE,
    empresa_cnpj text NOT NULL REFERENCES geral.empresa(cnpj)
);

CREATE TABLE IF NOT EXISTS eventual.documento_veiculo (
    id integer PRIMARY KEY REFERENCES eventual.documento(id) ON DELETE CASCADE,
    veiculo_placa text NOT NULL REFERENCES geral.veiculo(placa)
);

CREATE TABLE IF NOT EXISTS eventual.documento_motorista (
    id integer PRIMARY KEY REFERENCES eventual.documento(id) ON DELETE CASCADE,
    motorista_id integer NOT NULL REFERENCES eventual.motorista(id)
);

CREATE TABLE IF NOT EXISTS eventual.submissao (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entidade_tipo text NOT NULL,
    entidade_id text NOT NULL,
    status text NOT NULL,
    submissao_origem_id integer REFERENCES eventual.submissao(id),
    criado_em timestamp without time zone NOT NULL DEFAULT now(),
    atualizado_em timestamp without time zone NOT NULL DEFAULT now(),
    submetido_em timestamp without time zone,
    finalizado_em timestamp without time zone,
    criado_por text,
    analista_atual text REFERENCES web.usuario(email),
    observacao_analista text
);

CREATE INDEX IF NOT EXISTS idx_submissao_entidade_status
    ON eventual.submissao (entidade_tipo, entidade_id, status);

CREATE TABLE IF NOT EXISTS eventual.submissao_dados (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submissao_id integer NOT NULL UNIQUE REFERENCES eventual.submissao(id) ON DELETE CASCADE,
    dados_propostos jsonb NOT NULL,
    hash_dados text,
    carregado_do_live boolean NOT NULL DEFAULT false,
    status_revisao text NOT NULL,
    motivo_rejeicao text,
    revisado_por text REFERENCES web.usuario(email),
    revisado_em timestamp without time zone,
    criado_em timestamp without time zone NOT NULL DEFAULT now(),
    atualizado_em timestamp without time zone NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS eventual.submissao_documento (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submissao_id integer NOT NULL REFERENCES eventual.submissao(id) ON DELETE CASCADE,
    documento_id integer NOT NULL REFERENCES eventual.documento(id) ON DELETE CASCADE,
    documento_tipo_nome text NOT NULL REFERENCES eventual.documento_tipo(nome),
    obrigatorio_snapshot boolean NOT NULL DEFAULT false,
    validade_informada date,
    status_revisao text NOT NULL,
    motivo_rejeicao text,
    revisado_por text REFERENCES web.usuario(email),
    revisado_em timestamp without time zone,
    ativo_na_submissao boolean NOT NULL DEFAULT true,
    carregado_de_documento_atual boolean NOT NULL DEFAULT false,
    substitui_submissao_documento_id integer REFERENCES eventual.submissao_documento(id),
    criado_em timestamp without time zone NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_submissao_documento_submissao
    ON eventual.submissao_documento (submissao_id);

CREATE INDEX IF NOT EXISTS idx_submissao_documento_tipo_ativo
    ON eventual.submissao_documento (submissao_id, documento_tipo_nome, ativo_na_submissao);

CREATE TABLE IF NOT EXISTS eventual.entidade_documento_atual (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entidade_tipo text NOT NULL,
    entidade_id text NOT NULL,
    documento_tipo_nome text NOT NULL REFERENCES eventual.documento_tipo(nome),
    documento_id integer NOT NULL REFERENCES eventual.documento(id),
    submissao_documento_id integer NOT NULL REFERENCES eventual.submissao_documento(id),
    submissao_id integer NOT NULL REFERENCES eventual.submissao(id),
    definido_em timestamp without time zone NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_entidade_documento_atual_entidade_tipo
    ON eventual.entidade_documento_atual (entidade_tipo, entidade_id, documento_tipo_nome);

CREATE TABLE IF NOT EXISTS eventual.submissao_evento (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submissao_id integer NOT NULL REFERENCES eventual.submissao(id) ON DELETE CASCADE,
    tipo_evento text NOT NULL,
    descricao text,
    usuario_email text REFERENCES web.usuario(email),
    criado_em timestamp without time zone NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_submissao_evento_submissao
    ON eventual.submissao_evento (submissao_id, criado_em);

CREATE OR REPLACE VIEW eventual.v_pendencia_atual AS
SELECT DISTINCT ON (fp.entidade_tipo, fp.entidade_id)
    fp.id,
    fp.entidade_tipo,
    fp.entidade_id,
    fp.status,
    fp.analista,
    fp.criado_em,
    fp.motivo,
    fp.dados_propostos
FROM eventual.fluxo_pendencia fp
ORDER BY fp.entidade_tipo, fp.entidade_id, fp.criado_em DESC, fp.id DESC;
